/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app/organizations/index'
import { Route as AppOrganizationsNewRouteImport } from './routes/app/organizations/new'
import { Route as AppOrganizationsOrganizationIdRouteImport } from './routes/app/organizations/$organizationId'
import { Route as AppOrganizationsOrganizationIdIndexRouteImport } from './routes/app/organizations/$organizationId/index'
import { Route as AppOrganizationsOrganizationIdNewProcessRouteImport } from './routes/app/organizations/$organizationId/new-process'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsNewRoute = AppOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdRoute =
  AppOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsOrganizationIdIndexRoute =
  AppOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdNewProcessRoute =
  AppOrganizationsOrganizationIdNewProcessRouteImport.update({
    id: '/new-process',
    path: '/new-process',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/': typeof AppIndexRoute
  '/app/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRouteWithChildren
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/organizations/$organizationId/new-process': typeof AppOrganizationsOrganizationIdNewProcessRoute
  '/app/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AppIndexRoute
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/organizations/$organizationId/new-process': typeof AppOrganizationsOrganizationIdNewProcessRoute
  '/app/organizations/$organizationId': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/': typeof AppIndexRoute
  '/app/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRouteWithChildren
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/organizations/$organizationId/new-process': typeof AppOrganizationsOrganizationIdNewProcessRoute
  '/app/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/'
    | '/app/organizations/$organizationId'
    | '/app/organizations/new'
    | '/app/organizations/'
    | '/app/organizations/$organizationId/new-process'
    | '/app/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app'
    | '/app/organizations/new'
    | '/app/organizations'
    | '/app/organizations/$organizationId/new-process'
    | '/app/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/app/'
    | '/app/organizations/$organizationId'
    | '/app/organizations/new'
    | '/app/organizations/'
    | '/app/organizations/$organizationId/new-process'
    | '/app/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/new': {
      id: '/app/organizations/new'
      path: '/organizations/new'
      fullPath: '/app/organizations/new'
      preLoaderRoute: typeof AppOrganizationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$organizationId': {
      id: '/app/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/app/organizations/$organizationId'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$organizationId/': {
      id: '/app/organizations/$organizationId/'
      path: '/'
      fullPath: '/app/organizations/$organizationId/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/app/organizations/$organizationId/new-process': {
      id: '/app/organizations/$organizationId/new-process'
      path: '/new-process'
      fullPath: '/app/organizations/$organizationId/new-process'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdNewProcessRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
  }
}

interface AppOrganizationsOrganizationIdRouteChildren {
  AppOrganizationsOrganizationIdNewProcessRoute: typeof AppOrganizationsOrganizationIdNewProcessRoute
  AppOrganizationsOrganizationIdIndexRoute: typeof AppOrganizationsOrganizationIdIndexRoute
}

const AppOrganizationsOrganizationIdRouteChildren: AppOrganizationsOrganizationIdRouteChildren =
  {
    AppOrganizationsOrganizationIdNewProcessRoute:
      AppOrganizationsOrganizationIdNewProcessRoute,
    AppOrganizationsOrganizationIdIndexRoute:
      AppOrganizationsOrganizationIdIndexRoute,
  }

const AppOrganizationsOrganizationIdRouteWithChildren =
  AppOrganizationsOrganizationIdRoute._addFileChildren(
    AppOrganizationsOrganizationIdRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationsOrganizationIdRoute: typeof AppOrganizationsOrganizationIdRouteWithChildren
  AppOrganizationsNewRoute: typeof AppOrganizationsNewRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrganizationsOrganizationIdRoute:
    AppOrganizationsOrganizationIdRouteWithChildren,
  AppOrganizationsNewRoute: AppOrganizationsNewRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
